name = "codecrafters_redis"
version = "1.0.0"

[dependencies]
gleam_stdlib = "== 0.53.0"
gleam_erlang = "== 0.34.0"
gleam_otp = "== 0.16.1"
glisten = "== 7.0.1"
birl = "== 1.8.0"
argv = "== 1.0.2"
file_streams = "== 1.4.0"
filepath = "== 1.0.0"
gleam_regexp = "== 1.1.0"
ids = "== 0.14.0"
mug = "== 1.2.0"

[dev-dependencies]
gleeunit = "== 1.3.0"
